### PR TITLE
short URLs & gasless withdraw on close

### PR DESCRIPTION
**Pull request by CedarMist**
I switched the .env.development around, so .env.development is comitted which only includes the localhost URL, while the localnet deployment goes into .env.development.local and is .gitignore'd

 * [x] Upgrade to Solidity 0.8.28
 * [x] Use PNPM 9
 * [x] add sapphire-localnet for tests
 * [x] fix `/demo` url
 * [x] delete gasless voting info on poll deletion
 * [x] when poll is closed automatically broadcast the GasWithdrawTx events 
 * [ ] gasless poll closing?

### CODE REVIEW

**Review by csillag — APPROVED** [review]
Reviewed. Adjusted. LGTM. Merging.

**Comment by CedarMist** [comment]
So, with gasless voting refund works in the UI

image

But, figuring out why unit test failed, given it's the same underlying contract

**Comment by HarryR** [comment]
@csillag Are we good to merge this?

**Comment by csillag** [comment]
> @csillag Are we good to merge this?

@HarryR Please See my messages on slack! I thinkl found some problems...

**Pull request merged**
